sub female{
my($in)=@_;
  if(&sarvAxi($in)) {
      $pdgm="×ÏèÔÚ";
  }elsif($in=~/ÈŞÏèÔÚ"/){
      $pdgm="¨ÂèÂÏÈŞÏèÔÚ";
  }elsif($in=~/"ÄèÔÛÂÜÍÚ"/){
      $pdgm="ÄèÔÛÂÜÍÚ";
  }elsif($in=~/"ºÏÚ"/){
      $pdgm="ºÏÚ";
  }elsif($in=~/ÈÚ"/){
      $pdgm="µåÈÚ";
  }elsif($in=~/"ÊİÄèÅÛ"/){
      $pdgm="ÌÂÛ";
  }
#elsif($in=~/ÂÛ"/){
elsif($in=~/Û"/){
      $pdgm="ÌÂÛ";
  }elsif($in=~/"ÂèÏÛ"/){
      $pdgm="ÂèÏÛ";
  }elsif($in=~/"ÄèÔÛ"/){
      $pdgm="ÄèÔÛ";
  }elsif($in=~/"Ñ³èÖèÌÜ"/){
      $pdgm="Ñ³èÖèÌÜ";
 }elsif($in=~/"×èÂèÏÜ"/){
      $pdgm="×èÂèÏÜ";
  }elsif($in=~/ÕèÏÜ"/){
      $pdgm="ÕèÏÜ";
  }elsif($in=~/"³èÏåÖè½İ"/){
      $pdgm="³èÏåÖè½İ";
  }elsif($in=~/"ÊØİ"/){
      $pdgm="ÊØİ";
  }elsif($in =~ /Ü"/){
    if(($in=~/[ÏÖ]/) && ($in =~  /[ÏÖé][^Ñ¸¹º»¼½¾¿ÀÁÂÃÄÅÆÕ×]*"/)){
        $pdgm="µæÏÜ";
    } else {      
        $pdgm="ÆÄÜ";
    }
}elsif($in=~/"ÅáÆİ"/){
      $pdgm="ÅáÆİ";
  }elsif($in=~/"ËèÏŞ"/){
      $pdgm="ËèÏŞ";
  }elsif($in=~/Ş"/){
      $pdgm="×èÔÍÌèËŞ";
  }elsif($in=~/"×èÔ×ß"/){
      $pdgm="×èÔ×ß";
  }elsif($in=~/"ÌÚÂß"/){
      $pdgm="ÌÚÂß";
  }elsif($in=~/ß"/){
      $pdgm="ÌÚÂß";
  }elsif($in=~/å","Noun_f"/){
      $pdgm="ÄèÍå";
  }elsif($in=~/â","Noun_f"/){
      $pdgm="Ïâ";
  }elsif($in=~/æ","Noun_f"/){
      $pdgm="Ææ";
  } elsif($in =~/Ú"/){
    if(($in=~/[ÏÖ]/) && ($in =~ /[ÏÖ][^Ñ¸¹º»¼½¾¿ÀÁÂÃÄÅÆÕ×]*"/)){
        $pdgm="ÏÌÚ";
    } else {      
        $pdgm="×ÜÂÚ";
    }
  }elsif($in=~/ÆØè"/){
      $pdgm="¨ÈÚÆØè";
  }elsif($in=~/"¨ÖèÁÛØè"/){
      $pdgm="¨ÖèÁÛØè";
  }elsif($in=~/Øè"/){
      $pdgm="¨ÖèÁÛØè";
  }elsif($in=~/"ÄÛÔè"/){
      $pdgm="ÄÛÔè";
  }elsif($in=~/Ôè"/){
      $pdgm="ÄÛÔè";
  }elsif($in=~/"¸ÂİÏè"/){
      $pdgm="¸ÂİÏè";
  }elsif($in=~/µÛÏè"/){
      $pdgm="µÛÏè";
  }elsif($in=~/"ÈİÏè"/){
      $pdgm="ÈİÏè";
  }elsif($in=~/İÏè"/){
      $pdgm="ÈİÏè";
  }elsif($in=~/"³ÛÌè"/){
      $pdgm="³ÛÌè";
  }elsif($in=~/"¦ÄÌè"/){
      $pdgm="¦ÄÌè";
  }elsif($in=~/"ÂèÍÄè"/){
      $pdgm="ÂèÍÄè";
  }elsif($in=~/"ÂÄè"/){
      $pdgm="ÂÄè";
  }elsif($in=~/×ÏÛÂè"/){
      $pdgm="×ÏÛÂè";
  }elsif($in=~/Âè"/){
      $pdgm="È¾Âè";
  }elsif($in=~/×¢×Äè"/){
      $pdgm="×¢×Äè";
  }elsif($in=~/Äè"/){
      $pdgm="×¢×Äè";
  }elsif($in=~/"ÔÚ¸è"/){
      $pdgm="ÔÚ¸è";
  }elsif($in=~/¸è"/){
      $pdgm="ÔÚ¸è";
  }elsif($in=~/"¤Èè"/){
      $pdgm="¤Èè";
  }elsif($in=~/"ÄÛÕè"/){
      $pdgm="ÄÛÕè";
  }elsif($in=~/Õè"/){
      $pdgm="ÄÛÕè";
  }elsif($in=~/"ÂèÔÛÖè"/){
      $pdgm="ÂèÔÛÖè";
  }elsif($in=~/ÂèÔÛÖè"/){
      $pdgm="ÂèÔÛÖè";
  }elsif($in=~/"¥ÕÛÖè"/){
      $pdgm="¥ÕÛÖè";
  }elsif($in=~/ÛÖè"/){
      $pdgm="¥ÕÛÖè";
  }elsif($in=~/"×ºİÖè"/){
      $pdgm="×ºİÖè";
  }elsif($in=~/İÖè"/){
      $pdgm="×ºİÖè";
  }elsif($in=~/"¤Ä×è"/){
      $pdgm="¤Ä×è";
  }  
$pdgm;
}
1;
